### ISSUE TITLE
spaces when defining env variable

### ISSUE THREAD

**Issue by Jbarget** [dwyl/env2#20]
APIkey = 1234 (doesnt work)
APIkey=1234 (works)

environment variable isnt available when spaces are included in its definition

**Comment by nelsonic** [comment]
@Jbarget we've never had spaces in our keys, but if you feel this is a use-case you need, please submit a PR with the change. :+1:

**Comment by rjmk** [comment]
I think @Jbarget wanted to be able to use spaces without them being in the key (as perhttps://github.com/dwyl/env2/pull/21)

**Comment by nelsonic** [comment]
Understood. but what I want to *understand* is ***why*** would you *want* to store configuration with spaces?

**Comment by iteles** [comment]
My understanding is that the thought behind this issue is to proof **env2** against one of the more likely user errors (PEBCAK).

As @rjmk pointed out yesterday, it _is_ in the readme in bold, so it comes down to whether you want to encourage people to learn that configuration files shouldn't have spaces (seems sensible to me!) or just not allow this to be a stumbling block for newer users.

**Comment by nelsonic** [comment]
I'm *always* in favour of making things as simple as *possible* for ***beginners*** ... #**shoshin**
The reason I asked @Jbarget to submit the PR (*above*) is that when someone wants a feature, they should be prepared to at least defend its use-case.
The PR #21 @rjmk submitted only *partially* "*solves*" the problem.

But what we need *before* writing a *line* of code is *confirmation* from the customer/user that this *feature request* is going to somehow benefit the *majority* of *future users*.

Given that @Jbarget has not starred this repo or replied to my question I get the *feeling* that it's not *that* important to him. And that this issue was just created out of the initial frustration of it not working during the 2-day hackathon...

I can think of at *least* 10 other "*features*" this module *could* have ... but have resisted adding to its complexity because end-users have not requested them.

![less-is-the-new-more](https://cloud.githubusercontent.com/assets/194400/10261523/3d1f2e7c-6994-11e5-9b18-bbded9c48409.jpg)

**Comment by nelsonic** [comment]
PR merged. issue can be closed.
