### ISSUE TITLE
Could use codecov key as good application example of env2

### ISSUE THREAD

**Issue by Cleop** [dwyl/env2#41]
API keys may be a hard to understand example of using env2 because a lot of API applications would want more than local hosting. However in the case of using codecov, having your keys held locally would not cause problems for a live project and therefore could be a great example for env2.

**Comment by nelsonic** [comment]
@Cleop _great_ question!

> ***`Yes`***, a good use-case for an environment variable is a 3rd Party API token/key 
> ***`And`*** any other piece of data you need to keep secret (_and not accidentally push to GitHub_)

We tend to _not_ use the `codecov` key/token because our continuous integration service (Travis) does not require us to have one. This is how we use Codecov: https://github.com/dwyl/learn-istanbul#tracking-coverage-as-a-service (_without a token_)

However, if you _need_ to use the CodeCov token for a reason yes, you could store it in `.env` file. 👍 

See:
+ https://github.com/dwyl/learn-environment-variables
+ https://github.com/dwyl/learn-travis

**Comment by iteles** [comment]
I think the key here is that we could benefit from another usage example so we're not relying on the understanding of just one 👍

**Comment by Cleop** [comment]
Thanks for the note on Travis as in the instance that we used this, we were using Travis as well 👍

**Comment by nelsonic** [comment]
Closing as no longer relevant. ✅
